/**
 * blog_posts Collection Schema
 * Generated by Collection Builder
 * 2025-11-13T18:59:18.467Z
 *
 * This file is auto-generated. Manual modifications may be overwritten.
 */

import { boolean, jsonb, pgTable, serial, timestamp } from 'drizzle-orm/pg-core';

export const blogposts = pgTable('blog_posts', {
  id: serial('id').primaryKey(),
  test_json: jsonb('test_json'),
  status: boolean('status').default(false),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});
