/**
 * test_products Collection Schema
 * Generated by Collection Builder
 * 2025-11-12T21:54:30.249Z
 *
 * This file is auto-generated. Manual modifications may be overwritten.
 */

import { boolean, numeric, pgTable, serial, timestamp, varchar } from 'drizzle-orm/pg-core';

export const testproducts = pgTable('test_products', {
  id: serial('id').primaryKey(),
  name: varchar('name', { length: 255 }).notNull(),
  price: numeric('price', { precision: 10, scale: 2 }).notNull(),
  in_stock: boolean('in_stock').default(true),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});
