/**
 * Test Products Collection Tests
 * Generated by Collection Builder
 * 2025-11-12T21:54:30.248Z
 *
 * This file is auto-generated. You can modify these tests as needed.
 */

import { describe, it, expect, beforeAll, afterEach } from 'vitest';
import { db } from '@/db/client';
import { testproducts } from '@/db/schema/custom_collections/test-products';
import { eq } from 'drizzle-orm';

describe('Test Products Collection', () => {
  beforeAll(async () => {
    // Setup: Clear any existing test data
    await db.delete(testproducts).execute();
  });

  afterEach(async () => {
    // Cleanup: Clear test data after each test
    await db.delete(testproducts).execute();
  });

  it('should create a new test_products record', async () => {
    const [newRecord] = await db
      .insert(testproducts)
      .values({
      name: "Sample name",
      price: 99.99,
      in_stock: true,
      })
      .returning();

    expect(newRecord).toBeDefined();
    expect(newRecord.id).toBeGreaterThan(0);
  });

  it('should read test_products records', async () => {
    // Create a record first
    const [created] = await db
      .insert(testproducts)
      .values({
      name: "Sample name",
      price: 99.99,
      in_stock: true,
      })
      .returning();

    // Read all records
    const records = await db.select().from(testproducts).execute();

    expect(records).toHaveLength(1);
    expect(records[0].id).toBe(created.id);
  });

  it('should update a test_products record', async () => {
    // Create a record first
    const [created] = await db
      .insert(testproducts)
      .values({
      name: "Sample name",
      price: 99.99,
      in_stock: true,
      })
      .returning();

    // Update the record
    const [updated] = await db
      .update(testproducts)
      .set({ name: 'Updated value' })
      .where(eq(testproducts.id, created.id))
      .returning();

    expect(updated).toBeDefined();
    expect(updated.id).toBe(created.id);
  });

  it('should delete a test_products record', async () => {
    // Create a record first
    const [created] = await db
      .insert(testproducts)
      .values({
      name: "Sample name",
      price: 99.99,
      in_stock: true,
      })
      .returning();

    // Delete the record
    await db.delete(testproducts).where(eq(testproducts.id, created.id)).execute();

    // Verify deletion
    const records = await db.select().from(testproducts).execute();
    expect(records).toHaveLength(0);
  });

  it('should fail when required field "name" is missing', async () => {
    // Attempt to create record without required field
    const invalidData = {
      price: 99.99,
      in_stock: true,
    };

    await expect(async () => {
      await db.insert(testproducts).values(invalidData as any).execute();
    }).rejects.toThrow();
  });
});