-- Create test_products table
-- Generated by Collection Builder
-- 2025-11-12T21:54:30.249Z

CREATE TABLE IF NOT EXISTS test_products (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL DEFAULT null,
  price NUMERIC(10, 2) NOT NULL DEFAULT null,
  in_stock BOOLEAN DEFAULT 'true',
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
