/**
 * blog posts Collection Tests
 * Generated by Collection Builder
 * 2025-11-13T18:59:18.467Z
 *
 * This file is auto-generated. You can modify these tests as needed.
 */

import { describe, it, expect, beforeAll, afterEach } from 'vitest';
import { db } from '@/db/client';
import { blogposts } from '@/db/schema/custom_collections/blog-posts';
import { eq } from 'drizzle-orm';

describe('blog posts Collection', () => {
  beforeAll(async () => {
    // Setup: Clear any existing test data
    await db.delete(blogposts).execute();
  });

  afterEach(async () => {
    // Cleanup: Clear test data after each test
    await db.delete(blogposts).execute();
  });

  it('should create a new blog_posts record', async () => {
    const [newRecord] = await db
      .insert(blogposts)
      .values({
      test_json: { key: 'value' },
      status: true,
      })
      .returning();

    expect(newRecord).toBeDefined();
    expect(newRecord!.id).toBeGreaterThan(0);
  });

  it('should read blog_posts records', async () => {
    // Create a record first
    const [created] = await db
      .insert(blogposts)
      .values({
      test_json: { key: 'value' },
      status: true,
      })
      .returning();

    expect(created).toBeDefined();

    // Read all records
    const records = await db.select().from(blogposts).execute();

    expect(records).toHaveLength(1);
    expect(records[0]!.id).toBe(created!.id);
  });

  it('should update a blog_posts record', async () => {
    // Create a record first
    const [created] = await db
      .insert(blogposts)
      .values({
      test_json: { key: 'value' },
      status: true,
      })
      .returning();

    expect(created).toBeDefined();

    // Update the record
    const [updated] = await db
      .update(blogposts)
      .set({ test_json: { key: 'value' } })
      .where(eq(blogposts.id, created!.id))
      .returning();

    expect(updated).toBeDefined();
    expect(updated!.id).toBe(created!.id);
  });

  it('should delete a blog_posts record', async () => {
    // Create a record first
    const [created] = await db
      .insert(blogposts)
      .values({
      test_json: { key: 'value' },
      status: true,
      })
      .returning();

    expect(created).toBeDefined();

    // Delete the record
    await db.delete(blogposts).where(eq(blogposts.id, created!.id)).execute();

    // Verify deletion
    const records = await db.select().from(blogposts).execute();
    expect(records).toHaveLength(0);
  });
});